=== shaiyona336/S_Emulator/engine/xsd/S-Emulator-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="S-Functions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="S-Function" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="S-Function">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="S-Instructions"/>
			</xs:sequence>
			<xs:attribute name="user-string" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="S-Variable" type="xs:string"/>
	<xs:element name="S-Program">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="S-Instructions"/>
				<xs:element ref="S-Functions" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="S-Label" type="xs:string"/>
	<xs:element name="S-Instructions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="S-Instruction" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="S-Instruction-Arguments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="S-Instruction-Argument" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="S-Instruction-Argument">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="S-Instruction">
		<xs:complexType>
			<xs:all>
				<xs:element ref="S-Variable"/>
				<xs:element ref="S-Instruction-Arguments" minOccurs="0"/>
				<xs:element ref="S-Label" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="basic"/>
						<xs:enumeration value="synthetic"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="NEUTRAL"/>
						<xs:enumeration value="INCREASE"/>
						<xs:enumeration value="DECREASE"/>
						<xs:enumeration value="JUMP_NOT_ZERO"/>
						<xs:enumeration value="ZERO_VARIABLE"/>
						<xs:enumeration value="ASSIGNMENT"/>
						<xs:enumeration value="GOTO_LABEL"/>
						<xs:enumeration value="CONSTANT_ASSIGNMENT"/>
						<xs:enumeration value="JUMP_ZERO"/>
						<xs:enumeration value="JUMP_EQUAL_CONSTANT"/>
						<xs:enumeration value="JUMP_EQUAL_VARIABLE"/>
						<xs:enumeration value="QUOTE"/>
						<xs:enumeration value="JUMP_EQUAL_FUNCTION"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== shaiyona336/S_Emulator/resources/composition.xml
<?xml version="1.0" encoding="UTF-8"?>
<S-Program name="f(x) = 7 - (x+1)" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S-Emulator-v2.xsd">
	<S-Instructions>
	
		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>y</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="Minus"/>
				<S-Instruction-Argument name="functionArguments" value="(Const7),(Successor,x1)"/>
			</S-Instruction-Arguments>
		</S-Instruction>		
		
	</S-Instructions>
	<S-Functions>
	
		<S-Function name="Successor" user-string="S">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
				
			</S-Instructions>
		</S-Function>

		<S-Function name="Const7" user-string="CONST-7">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="CONSTANT_ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="constantValue" value="7"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
			</S-Instructions>
		</S-Function>
		
		<S-Function name="Minus" user-string="-">		
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x1"></S-Instruction-Argument>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x2"></S-Instruction-Argument>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>z1</S-Variable>
					<S-Label>L3</S-Label>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L1"/>
					</S-Instruction-Arguments>
				</S-Instruction>

				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>

				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>y</S-Variable>
					<S-Label>L1</S-Label>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L2"/>
					</S-Instruction-Arguments>
				</S-Instruction>

				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
								
				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>y</S-Variable>
					<S-Label>L2</S-Label>
				</S-Instruction>

				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>z1</S-Variable>
				</S-Instruction>
						
				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="L3"/>
					</S-Instruction-Arguments>
				</S-Instruction>

			</S-Instructions>
		</S-Function>
	</S-Functions>
</S-Program>

=== shaiyona336/S_Emulator/resources/self-composition.xml
<?xml version="1.0" encoding="UTF-8"?>
<S-Program name="f(x)=x+2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S-Emulator-v2.xsd">
	<S-Instructions>
		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>y</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="Successor"/>
				<S-Instruction-Argument name="functionArguments" value="(Successor,x1)"/>
			</S-Instruction-Arguments>
		</S-Instruction>		
	</S-Instructions>
	<S-Functions>
		<S-Function name="Successor" user-string="S">
			<S-Instructions>
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
			</S-Instructions>
		</S-Function>
	</S-Functions>
</S-Program>

=== shaiyona336/S_Emulator/resources/divide.xml
<?xml version="1.0" encoding="UTF-8"?>
<S-Program name="Divide" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S-Emulator-v2.xsd">
	<S-Instructions>
	
		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>z2</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="Smaller_Than"/>
				<S-Instruction-Argument name="functionArguments" value="x1,x2"/>
			</S-Instruction-Arguments>
		</S-Instruction>
		
		<S-Instruction type="basic" name="JUMP_NOT_ZERO">
			<S-Variable>z2</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="JNZLabel" value="EXIT"/>
			</S-Instruction-Arguments>
		</S-Instruction>

		<S-Instruction type="synthetic" name="JUMP_ZERO">
			<S-Variable>x2</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="JZLabel" value="EXIT"/>
			</S-Instruction-Arguments>
		</S-Instruction>
		
		<S-Instruction type="synthetic" name="ASSIGNMENT">
			<S-Variable>z3</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="assignedVariable" value="x1"/>
			</S-Instruction-Arguments>
		</S-Instruction>

		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>z3</S-Variable>
			<S-Label>L1</S-Label>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="Minus"/>
				<S-Instruction-Argument name="functionArguments" value="z3,x2"/>
			</S-Instruction-Arguments>
		</S-Instruction>
		
		<S-Instruction type="basic" name="INCREASE">
			<S-Variable>z4</S-Variable>
		</S-Instruction>
	
		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>z1</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="AND"/>
				<S-Instruction-Argument name="functionArguments" value="(Bigger_Equal_Than,z3,x2),(NOT,(EQUAL,z3,(CONST0)))"/>
			</S-Instruction-Arguments>
		</S-Instruction>
	
		<S-Instruction type="basic" name="JUMP_NOT_ZERO">
			<S-Variable>z1</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="JNZLabel" value="L1"/>
			</S-Instruction-Arguments>
		</S-Instruction>
	
		<S-Instruction type="synthetic" name="ASSIGNMENT">
			<S-Variable>y</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="assignedVariable" value="z4"/>
			</S-Instruction-Arguments>
		</S-Instruction>
					
	</S-Instructions>
	<S-Functions>
		<S-Function name="Minus" user-string="-">
			<S-Instructions>
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x2"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>z1</S-Variable>
					<S-Label>L3</S-Label>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>y</S-Variable>
					<S-Label>L1</S-Label>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L2"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>y</S-Variable>
					<S-Label>L2</S-Label>
				</S-Instruction>
				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>z1</S-Variable>
				</S-Instruction>
				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="L3"/>
					</S-Instruction-Arguments>
				</S-Instruction>
			</S-Instructions>
		</S-Function>

		<S-Function name="AND" user-string="&amp;&amp;">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="ZERO_VARIABLE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
	
				<S-Instruction type="synthetic" name="JUMP_ZERO">
					<S-Variable>x1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JZLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
	
				<S-Instruction type="synthetic" name="JUMP_ZERO">
					<S-Variable>x2</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JZLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>		
			
			</S-Instructions>
		</S-Function>

		<S-Function name="NOT" user-string="!">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="ZERO_VARIABLE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
				
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>x1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>		
				
			</S-Instructions>
		</S-Function>

		<S-Function name="EQUAL" user-string="==">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="QUOTE">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="functionName" value="AND"/>
						<S-Instruction-Argument name="functionArguments" value="(Smaller_Equal_Than,x1,x2),(Smaller_Equal_Than,x2,x1)"/>
					</S-Instruction-Arguments>
				</S-Instruction>
					
			</S-Instructions>
		</S-Function>

		<S-Function name="Smaller_Equal_Than" user-string="&lt;=">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="QUOTE">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="functionName" value="NOT"/>
						<S-Instruction-Argument name="functionArguments" value="(Minus,x1,x2)"/>
					</S-Instruction-Arguments>
				</S-Instruction>
							
			</S-Instructions>
		</S-Function>

		<S-Function name="Smaller_Than" user-string="&lt;">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="QUOTE">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="functionName" value="AND"/>
						<S-Instruction-Argument name="functionArguments" value="(Smaller_Equal_Than,x1,x2),(NOT,(EQUAL,x2,x1))"/>
					</S-Instruction-Arguments>
				</S-Instruction>
							
			</S-Instructions>
		</S-Function>

		<S-Function name="Bigger_Equal_Than" user-string="&gt;=">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="QUOTE">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="functionName" value="NOT"/>
						<S-Instruction-Argument name="functionArguments" value="(Smaller_Than,x1,x2)"/>
					</S-Instruction-Arguments>
				</S-Instruction>
							
			</S-Instructions>
		</S-Function>
		
		<S-Function name="CONST0" user-string="C0">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="CONSTANT_ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="constantValue" value="0"/>
					</S-Instruction-Arguments>
				</S-Instruction>			
				
			</S-Instructions>
		</S-Function>

	</S-Functions>
</S-Program>

=== shaiyona336/S_Emulator/resources/math.xml
<?xml version="1.0" encoding="UTF-8"?>
<S-Program name="Math Functions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S-Emulator-v2.xsd">
	<S-Instructions>
		<S-Instruction type="synthetic" name="NEUTRAL">
			<S-Variable>y</S-Variable>
		</S-Instruction>
	</S-Instructions>
	
	<S-Functions>
		<S-Function name="Minus" user-string="-">
			<S-Instructions>
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x2"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>z1</S-Variable>
					<S-Label>L3</S-Label>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>y</S-Variable>
					<S-Label>L1</S-Label>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L2"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>y</S-Variable>
					<S-Label>L2</S-Label>
				</S-Instruction>
				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>z1</S-Variable>
				</S-Instruction>
				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="L3"/>
					</S-Instruction-Arguments>
				</S-Instruction>
			</S-Instructions>
		</S-Function>	
		
		<S-Function name="Successor" user-string="S">
			<S-Instructions>
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>		
			</S-Instructions>			
		</S-Function>
		
		<S-Function name="Predecessor" user-string="P">
			<S-Instructions>
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>		
			</S-Instructions>			
		</S-Function>
		
		<S-Function name="Add" user-string="+">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="ZERO_VARIABLE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
		
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="synthetic" name="ASSIGNMENT">
					<S-Variable>z2</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="assignedVariable" value="x2"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>z1</S-Variable>
					<S-Label>L3</S-Label>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>z2</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L2"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>z3</S-Variable>
				</S-Instruction>
				
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>z3</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>z1</S-Variable>
					<S-Label>L1</S-Label>
				</S-Instruction>
				
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
				
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L1"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="synthetic" name="GOTO_LABEL">
					<S-Variable>z1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="gotoLabel" value="L3"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="DECREASE">
					<S-Variable>z2</S-Variable>
					<S-Label>L2</S-Label>
				</S-Instruction>
				
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
				
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>z2</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="L2"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
			</S-Instructions>
		</S-Function>
				
	</S-Functions>
	
</S-Program>

=== shaiyona336/S_Emulator/resources/predicates.xml
<?xml version="1.0" encoding="UTF-8"?>
<S-Program name="Predicates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S-Emulator-v2.xsd">
	<S-Instructions>
	
		<S-Instruction type="synthetic" name="NEUTRAL">
			<S-Variable>y</S-Variable>
		</S-Instruction>
					
	</S-Instructions>
	<S-Functions>

		<S-Function name="AND" user-string="&amp;&amp;">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="ZERO_VARIABLE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
	
				<S-Instruction type="synthetic" name="JUMP_ZERO">
					<S-Variable>x1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JZLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
	
				<S-Instruction type="synthetic" name="JUMP_ZERO">
					<S-Variable>x2</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JZLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>		
			
			</S-Instructions>
		</S-Function>

		<S-Function name="NOT" user-string="!">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="ZERO_VARIABLE">
					<S-Variable>y</S-Variable>
				</S-Instruction>
				
				<S-Instruction type="basic" name="JUMP_NOT_ZERO">
					<S-Variable>x1</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="JNZLabel" value="EXIT"/>
					</S-Instruction-Arguments>
				</S-Instruction>
				
				<S-Instruction type="basic" name="INCREASE">
					<S-Variable>y</S-Variable>
				</S-Instruction>		
				
			</S-Instructions>
		</S-Function>

		<S-Function name="EQUAL" user-string="==">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="QUOTE">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="functionName" value="AND"/>
						<S-Instruction-Argument name="functionArguments" value="(Smaller_Equal_Than,x1,x2),(Smaller_Equal_Than,x2,x1)"/>
					</S-Instruction-Arguments>
				</S-Instruction>
					
			</S-Instructions>
		</S-Function>

		<S-Function name="Smaller_Equal_Than" user-string="&lt;=">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="QUOTE">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="functionName" value="NOT"/>
						<S-Instruction-Argument name="functionArguments" value="(Minus,x1,x2)"/>
					</S-Instruction-Arguments>
				</S-Instruction>
							
			</S-Instructions>
		</S-Function>

		<S-Function name="Smaller_Than" user-string="&lt;">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="QUOTE">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="functionName" value="AND"/>
						<S-Instruction-Argument name="functionArguments" value="(Smaller_Equal_Than,x1,x2),(NOT,(EQUAL,x2,x1))"/>
					</S-Instruction-Arguments>
				</S-Instruction>
							
			</S-Instructions>
		</S-Function>

	</S-Functions>
</S-Program>

=== shaiyona336/S_Emulator/resources/remainder.xml
<?xml version="1.0" encoding="UTF-8"?>
<S-Program name="Reminder" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S-Emulator-v2.xsd">
	<S-Instructions>
	
		<S-Instruction type="synthetic" name="JUMP_ZERO">
			<S-Variable>x2</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="JZLabel" value="EXIT"/>
			</S-Instruction-Arguments>
		</S-Instruction>
			
		<S-Instruction type="synthetic" name="ASSIGNMENT">
			<S-Variable>z3</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="assignedVariable" value="x1"/>
			</S-Instruction-Arguments>
		</S-Instruction>
					
		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>z2</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="Smaller_Than"/>
				<S-Instruction-Argument name="functionArguments" value="x1,x2"/>
			</S-Instruction-Arguments>
		</S-Instruction>
		
		<S-Instruction type="basic" name="JUMP_NOT_ZERO">
			<S-Variable>z2</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="JNZLabel" value="L2"/>
			</S-Instruction-Arguments>
		</S-Instruction>
		
		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>z3</S-Variable>
			<S-Label>L1</S-Label>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="Minus"/>
				<S-Instruction-Argument name="functionArguments" value="z3,x2"/>
			</S-Instruction-Arguments>
		</S-Instruction>
		
		<S-Instruction type="basic" name="INCREASE">
			<S-Variable>z4</S-Variable>
		</S-Instruction>
	
		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>z1</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="AND"/>
				<S-Instruction-Argument name="functionArguments" value="(Bigger_Equal_Than,z3,x2),(NOT,(EQUAL,z3,(CONST0)))"/>
			</S-Instruction-Arguments>
		</S-Instruction>
	
		<S-Instruction type="basic" name="JUMP_NOT_ZERO">
			<S-Variable>z1</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="JNZLabel" value="L1"/>
			</S-Instruction-Arguments>
		</S-Instruction>
	
		<S-Instruction type="synthetic" name="ASSIGNMENT">
			<S-Variable>y</S-Variable>
			<S-Label>L2</S-Label>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="assignedVariable" value="z3"/>
			</S-Instruction-Arguments>
		</S-Instruction>
					
	</S-Instructions>
	<S-Functions>

		<S-Function name="CONST0" user-string="C0">
			<S-Instructions>
			
				<S-Instruction type="synthetic" name="CONSTANT_ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="constantValue" value="0"/>
					</S-Instruction-Arguments>
				</S-Instruction>			
				
			</S-Instructions>
		</S-Function>

	</S-Functions>
</S-Program>

=== shaiyona336/S_Emulator/resources/quotation.xml
<?xml version="1.0" encoding="UTF-8"?>
<S-Program name="f(x)=x+3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S-Emulator-v2.xsd">
	<S-Instructions>
		<S-Instruction type="synthetic" name="JUMP_EQUAL_FUNCTION">
			<S-Variable>x1</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="JEFunctionLabel" value="EXIT"/>
				<S-Instruction-Argument name="functionName" value="Const"/>
				<S-Instruction-Argument name="functionArguments" value=""/>
			</S-Instruction-Arguments>
		</S-Instruction>
		<S-Instruction type="synthetic" name="QUOTE">
			<S-Variable>z1</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="functionName" value="Const"/>
				<S-Instruction-Argument name="functionArguments" value=""/>
			</S-Instruction-Arguments>
		</S-Instruction>
		<S-Instruction type="synthetic" name="ASSIGNMENT">
			<S-Variable>y</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="assignedVariable" value="x1"/>
			</S-Instruction-Arguments>
		</S-Instruction>
		<S-Instruction type="basic" name="INCREASE">
			<S-Label>L1</S-Label>
			<S-Variable>y</S-Variable>
		</S-Instruction>
		<S-Instruction type="basic" name="DECREASE">
			<S-Variable>z1</S-Variable>
		</S-Instruction>
		<S-Instruction type="basic" name="JUMP_NOT_ZERO">
			<S-Variable>z1</S-Variable>
			<S-Instruction-Arguments>
				<S-Instruction-Argument name="JNZLabel" value="L1"/>
			</S-Instruction-Arguments>
		</S-Instruction>
	</S-Instructions>
	<S-Functions>
		<S-Function name="Const" user-string="CONST-3">
			<S-Instructions>
				<S-Instruction type="synthetic" name="CONSTANT_ASSIGNMENT">
					<S-Variable>y</S-Variable>
					<S-Instruction-Arguments>
						<S-Instruction-Argument name="constantValue" value="3"/>
					</S-Instruction-Arguments>
				</S-Instruction>
			</S-Instructions>
		</S-Function>
	</S-Functions>
</S-Program>
